version: '3.9'
services:
  api:
    build: .
    container_name: jobappman-api
    command: >
      sh -c "python manage.py createsuperuser --noinput;
      python manage.py migrate;
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/jobappman
    ports:
      - "8001:8000"
    environment:
      - DB_NAME=jobappman
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=jam-db
      - DJANGO_SUPERUSER_PASSWORD=sup3rUser
      - DJANGO_SUPERUSER_USERNAME=superuser
      - DJANGO_SUPERUSER_EMAIL=noemail@noemail.com
      - SECRET_KEY="django-insecure-fuv+)=j#cn0x+e%=n6j(wb$_y2rz-#u8t5$cjr7v#+)wd&ea8o"
    networks:
      jam:
        aliases:
          - 'api.jam.local'

networks:
  jam:
    external:
      name: jam