services:
  api:
    build: .
    container_name: jobappman-api
    command: >
      sh -c "python manage.py migrate --settings=core.settings.full;
      python manage.py runserver 0.0.0.0:8000 --settings=core.settings.full"
    volumes:
      - .:/jobappman
    ports:
      - "8001:8000"
    environment:
      - DB_NAME=jobappman
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=jam-db
      - DJANGO_SUPERUSER_PASSWORD=sup3rUser
      - DJANGO_SUPERUSER_USERNAME=superuser
      - DJANGO_SUPERUSER_EMAIL=noemail@noemail.com
      - SECRET_KEY=django1234
      - DEBUG=*
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    networks:
      jam:
        aliases:
          - "api.jam.local"

  extapi:
    build: .
    container_name: jobappman-extapi
    command: >
      sh -c "python manage.py migrate --settings=core.extapi;
      python manage.py runserver 0.0.0.0:8000 --settings=core.extapi"
    volumes:
      - .:/jobappman
    ports:
      - "8002:8000"
    environment:
      - DB_NAME=jobappman
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=jam-db
      - SECRET_KEY=django1234
      - DEBUG=*
    networks:
      jam:
        aliases:
          - "extapi.jam.local"

networks:
  jam:
    external: true
