version: '3.9'
services:
  web:
    build: .
    container_name: jobappman-api
    command: sh -c 'python manage.py migrate;python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/jobappman
    ports:
      - "8001:8000"
    environment:
      - DB_NAME=jobappman
      - DB_USER=root
      - DB_PASSWORD=root
