version: '3.9'
services:
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080

  web:
    build: ./jobappman
    container_name: jobappman-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./jobappman:/jobappman
    ports:
      - "8001:8000"
    environment:
      - DB_NAME=jobappman
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db