version: '3.9'
services:
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
    networks:
      - jam

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080

networks:
  jam:
    name: "jam"