version: '3.9'
services:
  client:
    build: .
    container_name: jobappman-client
    volumes:
      - .:/jam-client
    ports:
      - "81:81"
    command: sh -c "npm install && /jam-client/node_modules/@angular/cli/bin/ng.js serve --live-reload --host 0.0.0.0 --port 81"
    networks:
      jam:
        aliases:
          - 'client.jam.local'

networks:
  jam:
    external:
      name: jam