version: '3.9'
services:
  client:
    build: .
    container_name: jobappman-client
    volumes:
      - .:/jam-client
    ports:
      - "81:81"
    command: sh -c "ng serve --live-reload --host 0.0.0.0 --port 81"