"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if not os.getenv("DEBUG") else True

ALLOWED_HOSTS = ["localhost", "api.jam.local", "api.jam-app.com"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:81",
    "http://127.0.0.1:8000",
    "http://localhost:8001",
    "http://client.jam.local:81",
    "https://dashboard.jam-app.com"
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:81",
    "https://dashboard.jam-app.com"
]

# Cookie settings for cross-subdomain access
if DEBUG:
    # Localhost development: no domain restriction, allow HTTP
    CSRF_COOKIE_DOMAIN = None
    CSRF_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = False

    SESSION_COOKIE_DOMAIN = None
    SESSION_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SECURE = False
else:
    # Production: cross-subdomain cookies, HTTPS only
    CSRF_COOKIE_DOMAIN = ".jam-app.com"
    CSRF_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = False

    SESSION_COOKIE_DOMAIN = ".jam-app.com"
    SESSION_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SECURE = True

# Allow extension origins (chrome-extension:// and moz-extension://)
# Extension IDs are dynamic, so we allow all origins in development
# or use CORS_ORIGIN_REGEX_WHITELIST for more granular control (django-cors-headers 3.x)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    # Allow browser extension origins in production
    CORS_ORIGIN_REGEX_WHITELIST = [
        r"^chrome-extension://.*$",
        r"^moz-extension://.*$",
    ]
CORS_ALLOW_CREDENTIALS = True

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "knox",
    "core",
    "auth",
    "jam",
    "special",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": 3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "knox.auth.TokenAuthentication",
    ),
}

REST_KNOX = {
    'TOKEN_TTL': timedelta(hours=24),
    'AUTO_REFRESH': True,
    'AUTO_REFRESH_MAX_TTL': timedelta(days=30),
    'TOKEN_LIMIT_PER_USER': 5,
}

# Email / SMTP Configuration
EMAIL_HOST = os.getenv("JAM_EMAIL_HOST", "jam.com")
EMAIL_PORT = int(os.getenv("JAM_EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("JAM_EMAIL_USE_TLS", "True")
EMAIL_HOST_USER = os.getenv("JAM_EMAIL_HOST_USER", "jam@local.com")
EMAIL_HOST_PASSWORD = os.getenv("JAM_EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("JAM_DEFAULT_FROM_EMAIL", "jam@local.com")

# Frontend URL (used in password reset links)
FRONTEND_URL = os.getenv("JAM_FRONTEND_URL", "http://localhost:81")