# Generated by Django 4.0.4 on 2022-04-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('S', 'Start'), ('E', 'End'), ('D', 'Default')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('current_step', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jam.step')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jam.group')),
            ],
        ),
    ]
