# Generated by Django 4.0.4 on 2022-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0002_alter_jobapplication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
