# Generated by Django 4.0.4 on 2022-04-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0002_group_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='date',
        ),
    ]
