# Generated by Django 4.0.4 on 2022-04-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0005_timeline_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='date',
            field=models.DateField(),
        ),
    ]
