# Generated by Django 4.0.4 on 2022-05-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0006_alter_timeline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
