# Generated by Django 4.0.4 on 2022-05-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0008_step_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jam.jobapplication'),
        ),
    ]
