# Generated by Django 4.0.4 on 2022-05-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0009_alter_timeline_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='current_step',
            new_name='initial_step',
        ),
    ]
