# Generated by Django 4.0.4 on 2022-05-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0010_rename_current_step_jobapplication_initial_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='completed',
        ),
    ]
