# Generated by Django 4.0.4 on 2023-01-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0011_remove_jobapplication_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applied_through',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
