# Generated by Django 4.0.4 on 2023-01-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0013_jobapplication_external_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='date_relevant',
            field=models.BooleanField(default=True),
        ),
    ]
