# Generated by Django 4.0.4 on 2023-01-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0014_jobapplication_date_relevant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='date_relevant',
        ),
        migrations.AddField(
            model_name='timeline',
            name='date_relevant',
            field=models.BooleanField(default=True),
        ),
    ]
