# Generated by Django 4.0.4 on 2023-02-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0016_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
