# Generated by Django 4.0.4 on 2026-03-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0018_alter_lead_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
