# Generated by Django 4.0.4 on 2026-03-08 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0019_alter_jobapplication_external_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jam.group'),
        ),
    ]
