# Generated by Django 4.0.4 on 2026-03-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0020_lead_archived_lead_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='jam.lead'),
        ),
    ]
