# Generated by Django 4.0.4 on 2026-03-16 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0021_jobapplication_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='jam.jobapplication')),
            ],
        ),
    ]
