# Generated by Django 4.0.4 on 2026-03-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0022_jobadsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='position',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
