# Generated by Django 4.2 on 2026-05-02 07:21

from django.conf import settings
from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserProfile = apps.get_model('jam', 'UserProfile')
    
    # Find all users without a profile and create one for each
    users_without_profiles = User.objects.exclude(
        profile__isnull=False
    )
    for user in users_without_profiles:
        UserProfile.objects.create(user=user)


def reverse_create_missing_profiles(apps, schema_editor):
    UserProfile = apps.get_model('jam', 'UserProfile')
    # Delete all profiles that were auto-created (those with no other data)
    # This is a no-op since we can't distinguish auto-created from manually created
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jam', '0024_userprofile_cv_jobapplication_cv_used'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles, reverse_create_missing_profiles),
    ]
