# Generated by Django 4.2 on 2026-05-02 08:03

from django.db import migrations, models
import jam.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0025_backfill_user_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(upload_to='server_data/files/', validators=[jam.validators.validate_cv_file]),
        ),
    ]
