# Generated by Django 4.2 on 2026-06-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0026_alter_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
