# Generated by Django 4.2 on 2026-07-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0027_lead_generated_alter_lead_date_alter_lead_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='initial_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jam.step'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jam.step'),
        ),
    ]
