# Generated by Django 4.2 on 2026-07-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0028_alter_jobapplication_initial_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='jam.lead')),
            ],
        ),
    ]
