# Generated by Django 4.2 on 2026-08-16 12:25

from django.db import migrations, models
import django.db.models.deletion
import jam.validators


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0006_leadgenerationrequest_additional_comment_and_more'),
        ('jam', '0031_jobappfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='generation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_leads', to='special.leadgenerationrequest'),
        ),
        migrations.AlterField(
            model_name='jobappfile',
            name='file',
            field=models.FileField(upload_to='server_data/jobapp_files/', validators=[jam.validators.validate_job_app_file]),
        ),
    ]
