# Generated by Django 4.2 on 2026-05-13

import json
import os
from django.db import migrations


def load_reference_data(apps, schema_editor):
    Industry = apps.get_model('special', 'Industry')
    ExperienceLevel = apps.get_model('special', 'ExperienceLevel')
    Role = apps.get_model('special', 'Role')

    data_dir = os.path.join(os.path.dirname(__file__), '..', 'data')

    # Load industries
    industries_path = os.path.join(data_dir, 'industries.json')
    with open(industries_path, 'r', encoding='utf-8') as f:
        industries_data = json.load(f)
    for item in industries_data:
        Industry.objects.create(name=item['name'], slug=item['slug'])

    # Load experience levels
    levels_path = os.path.join(data_dir, 'experience_levels.json')
    with open(levels_path, 'r', encoding='utf-8') as f:
        levels_data = json.load(f)
    for item in levels_data:
        ExperienceLevel.objects.create(name=item['name'], slug=item['slug'])

    # Load roles
    roles_path = os.path.join(data_dir, 'roles.json')
    with open(roles_path, 'r', encoding='utf-8') as f:
        roles_data = json.load(f)
    for item in roles_data:
        Role.objects.create(name=item['name'], slug=item['slug'])


def unload_reference_data(apps, schema_editor):
    Industry = apps.get_model('special', 'Industry')
    ExperienceLevel = apps.get_model('special', 'ExperienceLevel')
    Role = apps.get_model('special', 'Role')

    Industry.objects.all().delete()
    ExperienceLevel.objects.all().delete()
    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_reference_data, unload_reference_data),
    ]
