# Generated by Django 4.2 on 2026-07-09 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0028_alter_jobapplication_initial_step_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('special', '0004_load_country_city_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='cvreview',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'CV reviews'},
        ),
        migrations.CreateModel(
            name='CoverLetterGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_requests', to='jam.cv')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_requests', to='jam.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
