# Generated by Django 4.2 on 2026-08-16 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('special', '0005_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgenerationrequest',
            name='additional_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='leadgenerationrequest',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadgenerationrequest',
            name='leads_generated_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadgenerationrequest',
            name='num_leads',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.CreateModel(
            name='ScheduledLeadGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_leads_only', models.BooleanField(default=False)),
                ('modes', models.JSONField(default=list)),
                ('company_sizes', models.JSONField(default=list)),
                ('num_leads', models.PositiveIntegerField(default=15)),
                ('additional_comment', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cities', models.ManyToManyField(blank=True, related_name='scheduled_lead_requests', to='special.city')),
                ('countries', models.ManyToManyField(blank=True, related_name='scheduled_lead_requests', to='special.country')),
                ('experience_level', models.ManyToManyField(blank=True, related_name='scheduled_lead_requests', to='special.experiencelevel')),
                ('industries', models.ManyToManyField(blank=True, related_name='scheduled_lead_requests', to='special.industry')),
                ('last_generation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='special.leadgenerationrequest')),
                ('roles', models.ManyToManyField(blank=True, related_name='scheduled_lead_requests', to='special.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_lead_generation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
