# Generated by Django 4.2 on 2026-08-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0007_add_more_industries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadgenerationrequest',
            name='is_scheduled',
        ),
        migrations.AddField(
            model_name='leadgenerationrequest',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_requests', to='special.scheduledleadgenerationrequest'),
        ),
        migrations.AlterField(
            model_name='leadgenerationrequest',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_cities', to='special.city'),
        ),
        migrations.AlterField(
            model_name='leadgenerationrequest',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_countries', to='special.country'),
        ),
        migrations.AlterField(
            model_name='leadgenerationrequest',
            name='experience_level',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_experience_levels', to='special.experiencelevel'),
        ),
        migrations.AlterField(
            model_name='leadgenerationrequest',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_industries', to='special.industry'),
        ),
        migrations.AlterField(
            model_name='leadgenerationrequest',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_roles', to='special.role'),
        ),
        migrations.AlterField(
            model_name='scheduledleadgenerationrequest',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_cities', to='special.city'),
        ),
        migrations.AlterField(
            model_name='scheduledleadgenerationrequest',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_countries', to='special.country'),
        ),
        migrations.AlterField(
            model_name='scheduledleadgenerationrequest',
            name='experience_level',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_experience_levels', to='special.experiencelevel'),
        ),
        migrations.AlterField(
            model_name='scheduledleadgenerationrequest',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_industries', to='special.industry'),
        ),
        migrations.AlterField(
            model_name='scheduledleadgenerationrequest',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_roles', to='special.role'),
        ),
    ]
